### ISSUE TITLE
Travisからherokuへのデプロイができなくなっている問題を解消

### ISSUE THREAD

**Issue by shoma2da** [handshakejp/webui#26]
https://travis-ci.org/handshakejp/webui/builds/46308217

このへんかな？↓↓↓↓↓
```
       Running: rake assets:precompile
       rake aborted!
       NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x007fbcfb78edc0>
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/railtie/configuration.rb:95:in `method_missing'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/config/environments/production.rb:78:in `block in <top (required)>'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `instance_eval'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/railtie.rb:210:in `configure'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/config/environments/production.rb:1:in `<top (required)>'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:597:in `each'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:597:in `block in <class:Engine>'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/config/environment.rb:5:in `<top (required)>'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
       /tmp/build_283ba488450ef5cf671f57b42d0d7dc8/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app
```

**Comment by shoma2da** [comment]
マージしたときにdeployに失敗していたので先にこれをやっちゃいます。
