### ISSUE TITLE
本番環境でエラーが出てるので直す

### ISSUE THREAD

**Issue by shoma2da** [handshakejp/webui#65]
http://handshakejp.herokuapp.com/

以下のようなエラーが出てる

```bash
$ heroku logs --tail

# some logs are here...

2015-04-01T12:55:51.723667+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=handshakejp.herokuapp.com request_id=52ca54ea-4be7-4486-a5e0-4a1c6f4f2f8c fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T12:55:52.302840+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=handshakejp.herokuapp.com request_id=dcf0eecb-d06b-4359-a9c6-d9dcbf9da4a8 fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T12:55:52.722099+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=handshakejp.herokuapp.com request_id=61f8637c-a136-4779-a947-7ed5d91b222c fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T12:56:54.219052+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=handshakejp.herokuapp.com request_id=976998f7-573d-4c7f-8e29-102576b2bc8f fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T12:56:55.010436+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=handshakejp.herokuapp.com request_id=d2b18f55-bf28-45f5-b28a-bf97ef089e92 fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T12:56:55.237822+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=handshakejp.herokuapp.com request_id=29ba643b-4571-4f7c-a8e7-458bf0a7cd1b fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T12:56:57.838372+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=handshakejp.herokuapp.com request_id=8330253d-5864-4c6e-9347-3a7f73b29116 fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T12:56:58.611876+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=handshakejp.herokuapp.com request_id=1aaf5c0f-5df3-4c7c-afdb-174db8858664 fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T13:04:24.469723+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=handshakejp.herokuapp.com request_id=f601e181-f7f3-4973-b7fc-38cdc3c06892 fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T13:04:25.050510+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=handshakejp.herokuapp.com request_id=b0a5b1d5-7ead-4be8-a895-44862969ad0c fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T13:06:40.096671+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=handshakejp.herokuapp.com request_id=1b675e95-8c98-41b9-943b-ed9c07b0cf04 fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
2015-04-01T13:06:41.348749+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=handshakejp.herokuapp.com request_id=cfe4dca8-0613-47fb-a0b7-1c48939f9577 fwd="126.6.19.136" dyno= connect= service= status=503 bytes=
```

**Comment by shoma2da** [comment]
関係あるのこっちだったっぽい
```
2015-03-28T14:53:47.180341+00:00 app[web.1]: /app/app/models/application.rb:2:in `<class:Application>': uninitialized constant Application::ActiveModel (NameError)
2015-03-28T14:53:47.180365+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
2015-03-28T14:53:47.180376+00:00 app[web.1]: 	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
2015-03-28T14:53:47.180400+00:00 app[web.1]: 	from /app/config.ru:3:in `require'
2015-03-28T14:53:47.180407+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2015-03-28T14:53:47.180411+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
2015-03-28T14:53:47.180413+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2015-03-28T14:53:47.180350+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `each'
2015-03-28T14:53:47.180370+00:00 app[web.1]: 	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
2015-03-28T14:53:47.180379+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
2015-03-28T14:53:47.180402+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
```
